import { useEffect, useState } from 'react'
import {
  formatFileSize,
  getAttachmentLabel,
  getPreviewKind,
} from '../utils/filePreview'

const MAX_PREVIEW_ROWS = 30
const MAX_PREVIEW_COLUMNS = 10

const defaultPreviewText = {
  previewPanelAria: 'File preview',
  previewTabLabel: 'Preview',
  previewInfoTabLabel: 'Details',
  previewCloseAria: 'Close file preview',
  previewEmptyTitle: 'Pick a file to inspect',
  previewEmptyCopy: 'Inline previews and file details appear here.',
  previewInlineUnavailable: 'Inline preview is not available for this file type yet.',
  previewLoading: 'Loading preview',
  previewLoadError: 'Preview could not be loaded.',
  previewOpenLabel: 'Download',
  previewKindPdf: 'PDF',
  previewKindSpreadsheet: 'Spreadsheet',
  previewKindDocument: 'Document',
  previewKindPresentation: 'Presentation',
  previewKindFile: 'File',
  previewSourceLabel: 'Source',
  previewSourceGenerated: 'Generated by agent',
  previewSourceUploaded: 'Uploaded in chat',
  previewTypeLabel: 'Type',
  previewSizeLabel: 'Size',
  previewRowsLabel: 'Rows',
  previewColumnsLabel: 'Columns',
  previewSheetsLabel: 'Sheets',
  previewSheetEmpty: 'This sheet is empty.',
  previewSheetTabsAria: 'Workbook sheets',
  previewTableTruncated: 'Showing the first {rows} rows and {columns} columns.',
  previewDetailsTitle: 'File details',
}

const interpolate = (template, values) =>
  (typeof template === 'string' ? template : '').replace(/\{(\w+)\}/g, (_, key) => values[key] ?? '')

const createInitialSpreadsheetState = () => ({
  status: 'idle',
  sheets: [],
  error: '',
})

const getSourceLabel = (copy, source) => {
  if (source === 'artifact') {
    return copy.previewSourceGenerated
  }

  return copy.previewSourceUploaded
}

const getKindLabel = (copy, kind) => {
  if (kind === 'pdf') return copy.previewKindPdf
  if (kind === 'spreadsheet') return copy.previewKindSpreadsheet
  if (kind === 'document') return copy.previewKindDocument
  if (kind === 'presentation') return copy.previewKindPresentation
  return copy.previewKindFile
}

const getSheetMetrics = (rows) => {
  const normalizedRows = Array.isArray(rows)
    ? rows.map((row) => (Array.isArray(row) ? row : [row]))
    : []

  const columnCount = normalizedRows.reduce((max, row) => Math.max(max, row.length), 0)

  return {
    rowCount: normalizedRows.length,
    columnCount,
    rows: normalizedRows,
  }
}

const PreviewValue = ({ label, value }) => (
  <div className="preview-detail-card">
    <span className="preview-detail-label">{label}</span>
    <strong className="preview-detail-value">{value}</strong>
  </div>
)

const SpreadsheetPreview = ({
  copy,
  spreadsheetState,
  activeSheetName,
  onSelectSheet,
}) => {
  if (spreadsheetState.status === 'loading') {
    return (
      <div className="preview-state-card is-loading">
        <span className="preview-state-spinner" aria-hidden="true" />
        <p>{copy.previewLoading}</p>
      </div>
    )
  }

  if (spreadsheetState.status === 'error') {
    return (
      <div className="preview-state-card is-error">
        <p>{copy.previewLoadError}</p>
        {spreadsheetState.error ? <span>{spreadsheetState.error}</span> : null}
      </div>
    )
  }

  const sheets = spreadsheetState.sheets

  if (sheets.length === 0) {
    return (
      <div className="preview-state-card">
        <p>{copy.previewInlineUnavailable}</p>
      </div>
    )
  }

  const activeSheet = sheets.find((sheet) => sheet.name === activeSheetName) ?? sheets[0]
  const visibleColumnCount = Math.max(1, Math.min(activeSheet.columnCount, MAX_PREVIEW_COLUMNS))
  const visibleRows = activeSheet.rows.slice(0, MAX_PREVIEW_ROWS)
  const normalizedRows = visibleRows.map((row) =>
    Array.from({ length: visibleColumnCount }, (_, index) => row[index] ?? ''),
  )
  const headerRow =
    normalizedRows[0] && normalizedRows[0].some((value) => `${value}`.trim())
      ? normalizedRows[0]
      : Array.from({ length: visibleColumnCount }, (_, index) => `Column ${index + 1}`)
  const bodyRows =
    normalizedRows[0] && normalizedRows[0].some((value) => `${value}`.trim())
      ? normalizedRows.slice(1)
      : normalizedRows

  return (
    <div className="preview-spreadsheet">
      <div className="preview-sheet-toolbar">
        <div
          className="preview-sheet-tabs"
          role="tablist"
          aria-label={copy.previewSheetTabsAria}
        >
          {sheets.map((sheet) => (
            <button
              key={sheet.name}
              type="button"
              className={`preview-sheet-tab ${sheet.name === activeSheet.name ? 'is-active' : ''}`}
              role="tab"
              aria-selected={sheet.name === activeSheet.name}
              onClick={() => onSelectSheet(sheet.name)}
            >
              {sheet.name}
            </button>
          ))}
        </div>

        <div className="preview-sheet-stats" aria-hidden="true">
          <span>{copy.previewRowsLabel}: {activeSheet.rowCount}</span>
          <span>{copy.previewColumnsLabel}: {activeSheet.columnCount}</span>
        </div>
      </div>

      {activeSheet.rowCount === 0 ? (
        <div className="preview-state-card">
          <p>{copy.previewSheetEmpty}</p>
        </div>
      ) : (
        <>
          <div className="preview-table-shell">
            <table className="preview-table">
              <thead>
                <tr>
                  {headerRow.map((cell, index) => (
                    <th key={`${activeSheet.name}-header-${index}`}>{cell || `Column ${index + 1}`}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {bodyRows.map((row, rowIndex) => (
                  <tr key={`${activeSheet.name}-row-${rowIndex}`}>
                    {row.map((cell, cellIndex) => (
                      <td key={`${activeSheet.name}-${rowIndex}-${cellIndex}`}>{cell}</td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {(activeSheet.rowCount > MAX_PREVIEW_ROWS || activeSheet.columnCount > MAX_PREVIEW_COLUMNS) && (
            <p className="preview-table-note">
              {interpolate(copy.previewTableTruncated, {
                rows: MAX_PREVIEW_ROWS,
                columns: MAX_PREVIEW_COLUMNS,
              })}
            </p>
          )}
        </>
      )}
    </div>
  )
}

export default function FilePreviewPanel({ file, onClose, text = defaultPreviewText }) {
  const copy = { ...defaultPreviewText, ...text }
  const [activeTab, setActiveTab] = useState('preview')
  const [spreadsheetState, setSpreadsheetState] = useState(createInitialSpreadsheetState)
  const [activeSheetName, setActiveSheetName] = useState('')

  const previewKind = getPreviewKind(file)
  const details = [
    {
      label: copy.previewTypeLabel,
      value: getKindLabel(copy, previewKind),
    },
    {
      label: copy.previewSizeLabel,
      value: formatFileSize(file?.size ?? 0),
    },
    {
      label: copy.previewSourceLabel,
      value: getSourceLabel(copy, file?.source),
    },
  ]

  useEffect(() => {
    setActiveTab('preview')
    setSpreadsheetState(createInitialSpreadsheetState())
    setActiveSheetName('')
  }, [file?.downloadUrl, file?.name])

  useEffect(() => {
    if (previewKind !== 'spreadsheet' || !file?.downloadUrl) {
      return undefined
    }

    const controller = new AbortController()
    let isActive = true

    setSpreadsheetState({
      status: 'loading',
      sheets: [],
      error: '',
    })

    void (async () => {
      try {
        const [xlsx, response] = await Promise.all([
          import('xlsx'),
          fetch(file.downloadUrl, {
            signal: controller.signal,
          }),
        ])

        if (!response.ok) {
          throw new Error(`HTTP ${response.status}`)
        }

        const arrayBuffer = await response.arrayBuffer()
        const workbook = xlsx.read(arrayBuffer, { type: 'array' })
        const sheets = workbook.SheetNames.map((name) => {
          const worksheet = workbook.Sheets[name]
          const rows = xlsx.utils.sheet_to_json(worksheet, {
            header: 1,
            raw: false,
            defval: '',
            blankrows: false,
          })
          const metrics = getSheetMetrics(rows)

          return {
            name,
            ...metrics,
          }
        })

        if (!isActive) {
          return
        }

        setSpreadsheetState({
          status: 'ready',
          sheets,
          error: '',
        })

        if (sheets[0]) {
          setActiveSheetName(sheets[0].name)
        }
      } catch (error) {
        if (!isActive || error?.name === 'AbortError') {
          return
        }

        setSpreadsheetState({
          status: 'error',
          sheets: [],
          error: error?.message ?? '',
        })
      }
    })()

    return () => {
      isActive = false
      controller.abort()
    }
  }, [file?.downloadUrl, previewKind])

  if (!file) {
    return (
      <aside className="panel preview-panel" aria-label={copy.previewPanelAria}>
        <div className="preview-panel-empty">
          <span className="preview-empty-icon" aria-hidden="true">
            FILE
          </span>
          <h3>{copy.previewEmptyTitle}</h3>
          <p>{copy.previewEmptyCopy}</p>
        </div>
      </aside>
    )
  }

  return (
    <aside className="panel preview-panel" aria-label={copy.previewPanelAria}>
      <header className="preview-header">
        <div className="preview-file-lockup">
          <span className="preview-file-badge" aria-hidden="true">
            {getAttachmentLabel(file.name)}
          </span>
          <div className="preview-file-copy">
            <span className="preview-file-kicker">{getKindLabel(copy, previewKind)}</span>
            <h2 title={file.name}>{file.name}</h2>
          </div>
        </div>

        <div className="preview-header-actions">
          {file.downloadUrl ? (
            <a
              className="preview-open-link"
              href={file.downloadUrl}
              download
              target="_blank"
              rel="noreferrer"
            >
              {copy.previewOpenLabel}
            </a>
          ) : null}

          <button
            type="button"
            className="preview-close-btn"
            onClick={onClose}
            aria-label={copy.previewCloseAria}
          >
            <svg width="14" height="14" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 6l12 12M18 6l-12 12" />
            </svg>
          </button>
        </div>
      </header>

      <div className="preview-panel-tabs" role="tablist" aria-label={copy.previewPanelAria}>
        <button
          type="button"
          className={`preview-panel-tab ${activeTab === 'preview' ? 'is-active' : ''}`}
          role="tab"
          aria-selected={activeTab === 'preview'}
          onClick={() => setActiveTab('preview')}
        >
          {copy.previewTabLabel}
        </button>
        <button
          type="button"
          className={`preview-panel-tab ${activeTab === 'details' ? 'is-active' : ''}`}
          role="tab"
          aria-selected={activeTab === 'details'}
          onClick={() => setActiveTab('details')}
        >
          {copy.previewInfoTabLabel}
        </button>
      </div>

      <div className="preview-body">
        {activeTab === 'preview' ? (
          previewKind === 'pdf' && file.downloadUrl ? (
            <div className="preview-frame-shell">
              <iframe
                className="preview-pdf-frame"
                title={`${file.name} preview`}
                src={file.downloadUrl}
              />
            </div>
          ) : previewKind === 'spreadsheet' ? (
            <SpreadsheetPreview
              copy={copy}
              spreadsheetState={spreadsheetState}
              activeSheetName={activeSheetName}
              onSelectSheet={setActiveSheetName}
            />
          ) : (
            <div className="preview-state-card">
              <span className="preview-empty-icon" aria-hidden="true">
                {getAttachmentLabel(file.name)}
              </span>
              <p>{copy.previewInlineUnavailable}</p>
            </div>
          )
        ) : (
          <div className="preview-details">
            <h3>{copy.previewDetailsTitle}</h3>
            <div className="preview-detail-grid">
              {details.map((item) => (
                <PreviewValue key={item.label} label={item.label} value={item.value} />
              ))}
              {previewKind === 'spreadsheet' && spreadsheetState.sheets.length > 0 ? (
                <PreviewValue
                  label={copy.previewSheetsLabel}
                  value={`${spreadsheetState.sheets.length}`}
                />
              ) : null}
            </div>
          </div>
        )}
      </div>
    </aside>
  )
}
