import { useEffect, useState } from 'react'
import { parseDocumentPreview, parsePresentationPreview } from '../utils/officePreview'
import {
  formatFileSize,
  getAttachmentLabel,
  getPreviewKind,
  supportsStructuredDocumentPreview,
  supportsStructuredPresentationPreview,
} from '../utils/filePreview'

const MAX_PREVIEW_ROWS = 30
const MAX_PREVIEW_COLUMNS = 10

const defaultPreviewText = {
  previewPanelAria: 'File preview',
  previewTabLabel: 'Preview',
  previewInfoTabLabel: 'Details',
  previewCloseAria: 'Close file preview',
  previewEmptyTitle: 'Pick a file to inspect',
  previewEmptyCopy: 'Inline previews and file details appear here.',
  previewInlineUnavailable: 'Inline preview is not available for this file type yet.',
  previewLoading: 'Loading preview',
  previewLoadError: 'Preview could not be loaded.',
  previewOpenLabel: 'Download',
  previewKindPdf: 'PDF',
  previewKindSpreadsheet: 'Spreadsheet',
  previewKindDocument: 'Document',
  previewKindPresentation: 'Presentation',
  previewKindFile: 'File',
  previewSourceLabel: 'Source',
  previewSourceGenerated: 'Generated by agent',
  previewSourceUploaded: 'Uploaded in chat',
  previewTypeLabel: 'Type',
  previewSizeLabel: 'Size',
  previewRowsLabel: 'Rows',
  previewColumnsLabel: 'Columns',
  previewSheetsLabel: 'Sheets',
  previewSlidesLabel: 'Slides',
  previewParagraphsLabel: 'Paragraphs',
  previewWordsLabel: 'Words',
  previewSheetEmpty: 'This sheet is empty.',
  previewDocumentEmpty: 'This document does not contain extractable text.',
  previewPresentationEmpty: 'This presentation does not contain extractable text.',
  previewSlideEmpty: 'This slide does not contain extractable text.',
  previewSheetTabsAria: 'Workbook sheets',
  previewSlideTabsAria: 'Presentation slides',
  previewSlideLabel: 'Slide {index}',
  previewTableTruncated: 'Showing the first {rows} rows and {columns} columns.',
  previewDetailsTitle: 'File details',
}

const interpolate = (template, values) =>
  (typeof template === 'string' ? template : '').replace(/\{(\w+)\}/g, (_, key) => values[key] ?? '')

const createInitialSpreadsheetState = () => ({
  status: 'idle',
  sheets: [],
  error: '',
})

const createInitialDocumentState = () => ({
  status: 'idle',
  blocks: [],
  paragraphCount: 0,
  wordCount: 0,
  error: '',
})

const createInitialPresentationState = () => ({
  status: 'idle',
  slides: [],
  error: '',
})

const loadBinaryFile = async (downloadUrl, signal) => {
  const response = await fetch(downloadUrl, { signal })

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}`)
  }

  return response.arrayBuffer()
}

const getSourceLabel = (copy, source) => {
  if (source === 'artifact') {
    return copy.previewSourceGenerated
  }

  return copy.previewSourceUploaded
}

const getKindLabel = (copy, kind) => {
  if (kind === 'pdf') return copy.previewKindPdf
  if (kind === 'spreadsheet') return copy.previewKindSpreadsheet
  if (kind === 'document') return copy.previewKindDocument
  if (kind === 'presentation') return copy.previewKindPresentation
  return copy.previewKindFile
}

const getSheetMetrics = (rows) => {
  const normalizedRows = Array.isArray(rows)
    ? rows.map((row) => (Array.isArray(row) ? row : [row]))
    : []

  const columnCount = normalizedRows.reduce((max, row) => Math.max(max, row.length), 0)

  return {
    rowCount: normalizedRows.length,
    columnCount,
    rows: normalizedRows,
  }
}

const getSlideTitle = (copy, slide) =>
  slide?.title || interpolate(copy.previewSlideLabel, { index: slide?.index ?? 1 })

const getSlideTabLabel = (copy, slide) => {
  const title = getSlideTitle(copy, slide)

  if (title.length <= 22) {
    return title
  }

  return `${title.slice(0, 19).trimEnd()}...`
}

const PreviewValue = ({ label, value }) => (
  <div className="preview-detail-card">
    <span className="preview-detail-label">{label}</span>
    <strong className="preview-detail-value">{value}</strong>
  </div>
)

const DownloadIcon = () => (
  <svg
    className="preview-open-icon"
    width="16"
    height="16"
    fill="none"
    stroke="currentColor"
    viewBox="0 0 24 24"
    aria-hidden="true"
  >
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" d="M12 4v10m0 0l-4-4m4 4l4-4" />
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" d="M5 18h14" />
  </svg>
)

const AsyncPreviewState = ({ copy, state, emptyMessage }) => {
  if (state.status === 'loading') {
    return (
      <div className="preview-state-card is-loading">
        <span className="preview-state-spinner" aria-hidden="true" />
        <p>{copy.previewLoading}</p>
      </div>
    )
  }

  if (state.status === 'error') {
    return (
      <div className="preview-state-card is-error">
        <p>{copy.previewLoadError}</p>
        {state.error ? <span>{state.error}</span> : null}
      </div>
    )
  }

  return (
    <div className="preview-state-card">
      <p>{emptyMessage}</p>
    </div>
  )
}

const SpreadsheetPreview = ({
  copy,
  spreadsheetState,
  activeSheetName,
  onSelectSheet,
}) => {
  if (spreadsheetState.status !== 'ready') {
    return (
      <AsyncPreviewState
        copy={copy}
        state={spreadsheetState}
        emptyMessage={copy.previewInlineUnavailable}
      />
    )
  }

  const sheets = spreadsheetState.sheets

  if (sheets.length === 0) {
    return (
      <AsyncPreviewState
        copy={copy}
        state={spreadsheetState}
        emptyMessage={copy.previewInlineUnavailable}
      />
    )
  }

  const activeSheet = sheets.find((sheet) => sheet.name === activeSheetName) ?? sheets[0]
  const visibleColumnCount = Math.max(1, Math.min(activeSheet.columnCount, MAX_PREVIEW_COLUMNS))
  const visibleRows = activeSheet.rows.slice(0, MAX_PREVIEW_ROWS)
  const normalizedRows = visibleRows.map((row) =>
    Array.from({ length: visibleColumnCount }, (_, index) => row[index] ?? ''),
  )
  const headerRow =
    normalizedRows[0] && normalizedRows[0].some((value) => `${value}`.trim())
      ? normalizedRows[0]
      : Array.from({ length: visibleColumnCount }, (_, index) => `Column ${index + 1}`)
  const bodyRows =
    normalizedRows[0] && normalizedRows[0].some((value) => `${value}`.trim())
      ? normalizedRows.slice(1)
      : normalizedRows

  return (
    <div className="preview-spreadsheet">
      <div className="preview-sheet-toolbar">
        <div
          className="preview-sheet-tabs"
          role="tablist"
          aria-label={copy.previewSheetTabsAria}
        >
          {sheets.map((sheet) => (
            <button
              key={sheet.name}
              type="button"
              className={`preview-sheet-tab ${sheet.name === activeSheet.name ? 'is-active' : ''}`}
              role="tab"
              aria-selected={sheet.name === activeSheet.name}
              onClick={() => onSelectSheet(sheet.name)}
            >
              {sheet.name}
            </button>
          ))}
        </div>

        <div className="preview-sheet-stats" aria-hidden="true">
          <span>{copy.previewRowsLabel}: {activeSheet.rowCount}</span>
          <span>{copy.previewColumnsLabel}: {activeSheet.columnCount}</span>
        </div>
      </div>

      {activeSheet.rowCount === 0 ? (
        <div className="preview-state-card">
          <p>{copy.previewSheetEmpty}</p>
        </div>
      ) : (
        <>
          <div className="preview-table-shell">
            <table className="preview-table">
              <thead>
                <tr>
                  {headerRow.map((cell, index) => (
                    <th key={`${activeSheet.name}-header-${index}`}>{cell || `Column ${index + 1}`}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {bodyRows.map((row, rowIndex) => (
                  <tr key={`${activeSheet.name}-row-${rowIndex}`}>
                    {row.map((cell, cellIndex) => (
                      <td key={`${activeSheet.name}-${rowIndex}-${cellIndex}`}>{cell}</td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {(activeSheet.rowCount > MAX_PREVIEW_ROWS || activeSheet.columnCount > MAX_PREVIEW_COLUMNS) && (
            <p className="preview-table-note">
              {interpolate(copy.previewTableTruncated, {
                rows: MAX_PREVIEW_ROWS,
                columns: MAX_PREVIEW_COLUMNS,
              })}
            </p>
          )}
        </>
      )}
    </div>
  )
}

const DocumentPreview = ({ copy, documentState }) => {
  if (documentState.status !== 'ready') {
    return (
      <AsyncPreviewState
        copy={copy}
        state={documentState}
        emptyMessage={copy.previewInlineUnavailable}
      />
    )
  }

  if (documentState.blocks.length === 0) {
    return (
      <AsyncPreviewState
        copy={copy}
        state={documentState}
        emptyMessage={copy.previewDocumentEmpty}
      />
    )
  }

  return (
    <div className="preview-document">
      <div className="preview-document-stats" aria-hidden="true">
        <span>{copy.previewParagraphsLabel}: {documentState.paragraphCount}</span>
        <span>{copy.previewWordsLabel}: {documentState.wordCount}</span>
      </div>

      <div className="preview-document-shell">
        <article className="preview-document-body">
          {documentState.blocks.map((block) =>
            block.kind === 'heading' ? (
              <h4
                key={block.id}
                className={`preview-document-heading ${block.level > 1 ? 'is-subheading' : ''}`}
              >
                {block.text}
              </h4>
            ) : (
              <p key={block.id} className="preview-document-paragraph">
                {block.text}
              </p>
            ),
          )}
        </article>
      </div>
    </div>
  )
}

const PresentationPreview = ({
  copy,
  presentationState,
  activeSlideId,
  onSelectSlide,
}) => {
  if (presentationState.status !== 'ready') {
    return (
      <AsyncPreviewState
        copy={copy}
        state={presentationState}
        emptyMessage={copy.previewInlineUnavailable}
      />
    )
  }

  const slides = presentationState.slides

  if (slides.length === 0) {
    return (
      <AsyncPreviewState
        copy={copy}
        state={presentationState}
        emptyMessage={copy.previewPresentationEmpty}
      />
    )
  }

  const activeSlide = slides.find((slide) => slide.id === activeSlideId) ?? slides[0]

  return (
    <div className="preview-presentation">
      <div className="preview-sheet-toolbar">
        <div
          className="preview-sheet-tabs"
          role="tablist"
          aria-label={copy.previewSlideTabsAria}
        >
          {slides.map((slide) => (
            <button
              key={slide.id}
              type="button"
              className={`preview-sheet-tab ${slide.id === activeSlide.id ? 'is-active' : ''}`}
              role="tab"
              aria-selected={slide.id === activeSlide.id}
              onClick={() => onSelectSlide(slide.id)}
              title={getSlideTitle(copy, slide)}
            >
              {getSlideTabLabel(copy, slide)}
            </button>
          ))}
        </div>

        <div className="preview-sheet-stats" aria-hidden="true">
          <span>{copy.previewSlidesLabel}: {slides.length}</span>
        </div>
      </div>

      <div className="preview-slide-shell">
        <article className="preview-slide-card">
          <span className="preview-slide-kicker">
            {interpolate(copy.previewSlideLabel, { index: activeSlide.index })}
          </span>
          <h4 className="preview-slide-title">{getSlideTitle(copy, activeSlide)}</h4>

          {activeSlide.blocks.length > 0 ? (
            <div className="preview-slide-body">
              {activeSlide.blocks.map((block, index) => (
                <p key={`${activeSlide.id}-block-${index}`} className="preview-slide-paragraph">
                  {block}
                </p>
              ))}
            </div>
          ) : (
            <p className="preview-slide-empty">{copy.previewSlideEmpty}</p>
          )}
        </article>
      </div>
    </div>
  )
}

export default function FilePreviewPanel({ file, onClose, text = defaultPreviewText }) {
  const copy = { ...defaultPreviewText, ...text }
  const [activeTab, setActiveTab] = useState('preview')
  const [spreadsheetState, setSpreadsheetState] = useState(createInitialSpreadsheetState)
  const [documentState, setDocumentState] = useState(createInitialDocumentState)
  const [presentationState, setPresentationState] = useState(createInitialPresentationState)
  const [activeSheetName, setActiveSheetName] = useState('')
  const [activeSlideId, setActiveSlideId] = useState('')

  const previewKind = getPreviewKind(file)
  const canPreviewDocument = supportsStructuredDocumentPreview(file)
  const canPreviewPresentation = supportsStructuredPresentationPreview(file)

  useEffect(() => {
    setActiveTab('preview')
    setSpreadsheetState(createInitialSpreadsheetState())
    setDocumentState(createInitialDocumentState())
    setPresentationState(createInitialPresentationState())
    setActiveSheetName('')
    setActiveSlideId('')
  }, [file?.downloadUrl, file?.name])

  useEffect(() => {
    if (previewKind !== 'spreadsheet' || !file?.downloadUrl) {
      return undefined
    }

    const controller = new AbortController()
    let isActive = true

    setSpreadsheetState({
      status: 'loading',
      sheets: [],
      error: '',
    })

    void (async () => {
      try {
        const [xlsx, arrayBuffer] = await Promise.all([
          import('xlsx'),
          loadBinaryFile(file.downloadUrl, controller.signal),
        ])

        const workbook = xlsx.read(arrayBuffer, { type: 'array' })
        const sheets = workbook.SheetNames.map((name) => {
          const worksheet = workbook.Sheets[name]
          const rows = xlsx.utils.sheet_to_json(worksheet, {
            header: 1,
            raw: false,
            defval: '',
            blankrows: false,
          })
          const metrics = getSheetMetrics(rows)

          return {
            name,
            ...metrics,
          }
        })

        if (!isActive) {
          return
        }

        setSpreadsheetState({
          status: 'ready',
          sheets,
          error: '',
        })

        if (sheets[0]) {
          setActiveSheetName(sheets[0].name)
        }
      } catch (error) {
        if (!isActive || error?.name === 'AbortError') {
          return
        }

        setSpreadsheetState({
          status: 'error',
          sheets: [],
          error: error?.message ?? '',
        })
      }
    })()

    return () => {
      isActive = false
      controller.abort()
    }
  }, [file?.downloadUrl, previewKind])

  useEffect(() => {
    if (previewKind !== 'document' || !file?.downloadUrl || !canPreviewDocument) {
      return undefined
    }

    const controller = new AbortController()
    let isActive = true

    setDocumentState({
      status: 'loading',
      blocks: [],
      paragraphCount: 0,
      wordCount: 0,
      error: '',
    })

    void (async () => {
      try {
        const arrayBuffer = await loadBinaryFile(file.downloadUrl, controller.signal)
        const preview = parseDocumentPreview(arrayBuffer)

        if (!isActive) {
          return
        }

        setDocumentState({
          status: 'ready',
          ...preview,
          error: '',
        })
      } catch (error) {
        if (!isActive || error?.name === 'AbortError') {
          return
        }

        setDocumentState({
          status: 'error',
          blocks: [],
          paragraphCount: 0,
          wordCount: 0,
          error: error?.message ?? '',
        })
      }
    })()

    return () => {
      isActive = false
      controller.abort()
    }
  }, [canPreviewDocument, file?.downloadUrl, previewKind])

  useEffect(() => {
    if (previewKind !== 'presentation' || !file?.downloadUrl || !canPreviewPresentation) {
      return undefined
    }

    const controller = new AbortController()
    let isActive = true

    setPresentationState({
      status: 'loading',
      slides: [],
      error: '',
    })

    void (async () => {
      try {
        const arrayBuffer = await loadBinaryFile(file.downloadUrl, controller.signal)
        const preview = parsePresentationPreview(arrayBuffer)

        if (!isActive) {
          return
        }

        setPresentationState({
          status: 'ready',
          ...preview,
          error: '',
        })

        if (preview.slides[0]) {
          setActiveSlideId(preview.slides[0].id)
        }
      } catch (error) {
        if (!isActive || error?.name === 'AbortError') {
          return
        }

        setPresentationState({
          status: 'error',
          slides: [],
          error: error?.message ?? '',
        })
      }
    })()

    return () => {
      isActive = false
      controller.abort()
    }
  }, [canPreviewPresentation, file?.downloadUrl, previewKind])

  const details = [
    {
      label: copy.previewTypeLabel,
      value: getKindLabel(copy, previewKind),
    },
    {
      label: copy.previewSizeLabel,
      value: formatFileSize(file?.size ?? 0),
    },
    {
      label: copy.previewSourceLabel,
      value: getSourceLabel(copy, file?.source),
    },
  ]

  if (previewKind === 'spreadsheet' && spreadsheetState.sheets.length > 0) {
    details.push({
      label: copy.previewSheetsLabel,
      value: `${spreadsheetState.sheets.length}`,
    })
  }

  if (previewKind === 'document' && documentState.paragraphCount > 0) {
    details.push(
      {
        label: copy.previewParagraphsLabel,
        value: `${documentState.paragraphCount}`,
      },
      {
        label: copy.previewWordsLabel,
        value: `${documentState.wordCount}`,
      },
    )
  }

  if (previewKind === 'presentation' && presentationState.slides.length > 0) {
    details.push({
      label: copy.previewSlidesLabel,
      value: `${presentationState.slides.length}`,
    })
  }

  if (!file) {
    return (
      <aside className="panel preview-panel" aria-label={copy.previewPanelAria}>
        <div className="preview-panel-empty">
          <span className="preview-empty-icon" aria-hidden="true">
            FILE
          </span>
          <h3>{copy.previewEmptyTitle}</h3>
          <p>{copy.previewEmptyCopy}</p>
        </div>
      </aside>
    )
  }

  return (
    <aside className="panel preview-panel" aria-label={copy.previewPanelAria}>
      <header className="preview-header">
        <div className="preview-file-lockup">
          <span className="preview-file-badge" aria-hidden="true">
            {getAttachmentLabel(file.name)}
          </span>
          <div className="preview-file-copy">
            <span className="preview-file-kicker">{getKindLabel(copy, previewKind)}</span>
            <h2 title={file.name}>{file.name}</h2>
          </div>
        </div>

        <div className="preview-header-actions">
          {file.downloadUrl ? (
            <a
              className="preview-open-link is-icon-only"
              href={file.downloadUrl}
              download
              target="_blank"
              rel="noreferrer"
              aria-label={copy.previewOpenLabel}
              title={copy.previewOpenLabel}
            >
              <DownloadIcon />
            </a>
          ) : null}

          <button
            type="button"
            className="preview-close-btn"
            onClick={onClose}
            aria-label={copy.previewCloseAria}
          >
            <svg width="14" height="14" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 6l12 12M18 6l-12 12" />
            </svg>
          </button>
        </div>
      </header>

      <div className="preview-panel-tabs" role="tablist" aria-label={copy.previewPanelAria}>
        <button
          type="button"
          className={`preview-panel-tab ${activeTab === 'preview' ? 'is-active' : ''}`}
          role="tab"
          aria-selected={activeTab === 'preview'}
          onClick={() => setActiveTab('preview')}
        >
          {copy.previewTabLabel}
        </button>
        <button
          type="button"
          className={`preview-panel-tab ${activeTab === 'details' ? 'is-active' : ''}`}
          role="tab"
          aria-selected={activeTab === 'details'}
          onClick={() => setActiveTab('details')}
        >
          {copy.previewInfoTabLabel}
        </button>
      </div>

      <div className="preview-body">
        {activeTab === 'preview' ? (
          previewKind === 'pdf' && file.downloadUrl ? (
            <div className="preview-frame-shell">
              <iframe
                className="preview-pdf-frame"
                title={`${file.name} preview`}
                src={file.downloadUrl}
              />
            </div>
          ) : previewKind === 'spreadsheet' ? (
            <SpreadsheetPreview
              copy={copy}
              spreadsheetState={spreadsheetState}
              activeSheetName={activeSheetName}
              onSelectSheet={setActiveSheetName}
            />
          ) : previewKind === 'document' && canPreviewDocument ? (
            <DocumentPreview copy={copy} documentState={documentState} />
          ) : previewKind === 'presentation' && canPreviewPresentation ? (
            <PresentationPreview
              copy={copy}
              presentationState={presentationState}
              activeSlideId={activeSlideId}
              onSelectSlide={setActiveSlideId}
            />
          ) : (
            <div className="preview-state-card">
              <span className="preview-empty-icon" aria-hidden="true">
                {getAttachmentLabel(file.name)}
              </span>
              <p>{copy.previewInlineUnavailable}</p>
            </div>
          )
        ) : (
          <div className="preview-details">
            <h3>{copy.previewDetailsTitle}</h3>
            <div className="preview-detail-grid">
              {details.map((item) => (
                <PreviewValue key={item.label} label={item.label} value={item.value} />
              ))}
            </div>
          </div>
        )}
      </div>
    </aside>
  )
}
